version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:3000"
    volumes:
      - .:/go/src/app
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=one_repo_dev
      - DB_PORT=3306
  mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: one_repo_dev
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: